#!/usr/bin/env python3
"""Apply comprehensive EN->ZH translation to ML menu strings.

Translates .name, .help, .help2, and .choices strings.
Does NOT translate menu_add() first args (top-level menu names) or
select_menu_by_name() args (internal lookups).
"""
import re, glob, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Top-level menu names that must stay English
TOPLEVEL = {
    "Audio", "Expo", "Overlay", "Movie", "Shoot", "Focus",
    "Display", "Prefs", "Scripts", "Games", "Modules", "Debug",
    "Help", "VRAM", "Intervalometer", "LV Rec", "DotTune AFMA",
    "File Manager", "Movie tweaks", "List Keyframes",
}

# Comprehensive translation dictionary
DICT = {
    # === Choices / Options ===
    "FW default": "固件默认",
    "CBR": "CBR",
    "VBR (QScale)": "VBR (QScale)",
    "Separate WAV": "独立WAV",
    "Elapsed": "已用时间",
    "Remain.Card": "剩余卡空间",
    "Remain.4GB": "剩余4GB",
    "Hold AF button": "按住AF按钮",
    "Continuous": "连续",
    "Arrow keys": "方向键",
    "LCD sensor": "LCD传感器",
    "+ / -": "+ / -",
    "- / +": "- / +",
    "Simple": "简单",
    "Diffraction-aware": "衍射感知",
    "Luma": "亮度",
    "RGB": "RGB",
    "Luma Fast": "亮度快速",
    "Hide": "隐藏",
    "Always": "总是",
    "Photo only": "仅照片",
    "Strong edges": "强边缘",
    "Balanced": "均衡",
    "Fine details": "精细细节",
    "Blinking dots": "闪烁点",
    "Fine dots": "精细点",
    "Alpha blend": "Alpha混合",
    "Raw": "Raw",
    "Blue": "蓝色",
    "Cyan": "青色",
    "Magenta": "品红",
    "Yellow": "黄色",
    "Global Focus": "全局对焦",
    "Local Focus": "局部对焦",
    "Focus Ring": "对焦环",
    "FocusR+HalfS": "对焦环+半按",
    "Always On": "始终开启",
    "Zoom.REC": "录制时缩放",
    "Focus+ZREC": "对焦+录缩放",
    "ZoomIn (+)": "放大(+)",
    "Small": "小",
    "Medium": "中",
    "Large": "大",
    "FullScreen": "全屏",
    "Focus box": "对焦框",
    "Top-Left": "左上",
    "Top-Right": "右上",
    "Bottom-Right": "右下",
    "Bottom-Left": "左下",
    "Green Bars": "绿条",
    "SplitScreen": "裂像",
    "SS ZeroCross": "裂像过零",
    "Percent": "百分比",
    "0..255": "0..255",
    "RGB (HTML)": "RGB (HTML)",
    "RAW (EV)": "RAW (EV)",
    "RGB (Percent)": "RGB (百分比)",
    "Center": "中心",
    "Marshall": "Marshall",
    "SmallHD": "SmallHD",
    "50-55%": "50-55%",
    "67-72%": "67-72%",
    "Banding detection": "条带检测",
    "GreenScreen": "绿屏",
    "YUV-based, Luma": "YUV亮度",
    "YUV-based, RGB": "YUV RGB",
    "RAW-based (RGB)": "RAW RGB",
    "RAW HistoBar (MAX)": "RAW直方图(MAX)",
    "OFF": "关闭",
    "ON": "开启",
    "Dynamic Range": "动态范围",
    "ETTR hint": "ETTR提示",
    "Linear": "线性",
    "QuickReview": "快速回放",
    "ON, all modes": "开启(所有模式)",
    "Internal mic": "内置麦克风",
    "L:int R:ext": "左:内 右:外",
    "External stereo": "外部立体声",
    "L:int R:balanced": "左:内 右:平衡",
    "Auto int/ext": "自动内/外",
    "2 dB (digital)": "2 dB (数字)",
    "4 dB (digital)": "4 dB (数字)",
    "6 dB (digital)": "6 dB (数字)",
    "Bypass loading ML": "跳过加载ML",
    "Required to load ML": "需要加载ML",
    "Percentage": "百分比",
    "Busy tasks (ABS)": "繁忙任务(绝对)",
    "Busy tasks (REL)": "繁忙任务(相对)",
    "Leave unchanged": "保持不变",
    "Block during REC": "录制时阻止",
    "Hold during REC": "录制时保持",
    "HalfShutter": "半按快门",
    "Start/Stop": "开始/停止",
    "Start only": "仅开始",
    "Stop only": "仅停止",
    "Always ON": "始终开启",
    "Auto Snap": "自动抓拍",
    "Press SET": "按SET",
    "HalfS DblClick": "半按双击",
    "Adobe XMP": "Adobe XMP",
    "UFRaw": "UFRaw",
    "Burst": "连拍",
    "Burst, End Trigger": "连拍,末尾触发",
    "Best Focus": "最佳对焦",
    "Slit-Scan": "狭缝扫描",
    "Full-res": "全分辨率",
    "Full-res LV": "全分辨率LV",
    "Top->Bottom": "上->下",
    "Bottom->Top": "下->上",
    "Left->Right": "左->右",
    "Right->Left": "右->左",
    "Horizontal": "水平",
    "Half-shutter press": "半按快门",
    "Half-shutter release": "半按快门释放",
    "Delayed": "延迟",
    "DNG": "DNG",
    "MLV": "MLV",
    "Lossless DNG": "无损DNG",
    "Auto": "自动",
    "Canon": "佳能",
    "ML Grayscale": "ML灰度",
    "HaCKeD": "HaCKeD",
    "Hacked No Prev": "HaCKeD无预览",
    "None": "无",
    "Icon": "图标",
    "Debug": "调试",
    "2 sec.": "2秒",
    "4 sec.": "4秒",
    "10 sec.": "10秒",
    "16 MB": "16 MB",
    "32 MB": "32 MB",
    "64 MB": "64 MB",
    "128 MB": "128 MB",
    "256 MB": "256 MB",
    "512 MB": "512 MB",
    "1 GB": "1 GB",
    "Allow": "允许",
    "Real-time": "实时",
    "Framing": "取景",
    "Frozen LV": "冻结LV",
    "Half-shutter: start/pause": "半按:开始/暂停",
    "Half-shutter: hold": "半按:保持",
    "Half-shutter: pre only": "半按:仅预录",
    "Buffers": "缓冲区",
    "Buffer usage": "缓冲区使用",
    "10bpp": "10bpp",
    "12bpp": "12bpp",
    "14bpp": "14bpp",
    "14-bit": "14-bit",
    "12-bit": "12-bit",
    "10-bit": "10-bit",
    "14-bit lossless": "14-bit无损",
    "12-bit lossless": "12-bit无损",
    "11...8-bit lossless": "11...8-bit无损",
    "Auto range detection": "自动范围检测",
    "Linear -20..+20": "线性 -20..+20",
    "Disabled": "已禁用",
    "All lenses": "所有镜头",
    "This lens": "当前镜头",
    "Open submenu (Q)": "打开子菜单(Q)",
    "Edit values": "编辑值",
    "Edit in LiveView": "在实时取景中编辑",
    "Junkie mode": "Junkie模式",
    "Overlays (PLAY only)": "叠加(仅回放)",
    "Shortcuts (LV only)": "快捷键(仅LV)",

    # === Menu Names (sub-menu entries, NOT top-level) ===
    "Time Indicator": "时间指示器",
    "Time indicator": "时间指示器",
    "Trap Focus": "陷阱对焦",
    "Follow Focus": "跟随对焦",
    "Focus using": "对焦方式",
    "Focus End Point": "对焦终点",
    "Rack Focus": "移位对焦",
    "Focus Stacking": "焦点堆叠",
    "Run focus stack": "运行焦点堆叠",
    "Num. pics in front": "前方拍摄数",
    "Num. pics behind": "后方拍摄数",
    "Focus steps / picture": "每张对焦步数",
    "Flash Delay": "闪光延迟",
    "Focus Settings": "对焦设置",
    "Step Size": "步长",
    "Step Delay": "步进延迟",
    "Step Wait": "步进等待",
    "Left/Right dir": "左/右方向",
    "Up/Down dir": "上/下方向",
    "Start Delay": "启动延迟",
    "When recording": "录制时",
    "Use RAW zebras": "使用RAW斑马纹",
    "Raw zebra underexposure": "RAW斑马纹欠曝",
    "Grayscale image": "灰度图像",
    "Magic Zoom": "魔法缩放",
    "Position": "位置",
    "Magnification": "放大倍率",
    "Focus confirm": "对焦确认",
    "Ghost image": "幽灵图像",
    "Spot Position": "测光点位置",
    "Palette      ": "调色板      ",
    "Histogram type": "直方图类型",
    "RAW EV indicator": "RAW EV指示器",
    "Waveform Size": "波形图大小",
    "Level Indicator": "水平指示器",
    "Show Overlay FPS": "显示叠加FPS",
    "LV Display Presets": "LV显示预设",
    "Focus box settings": "对焦框设置",
    "Snap points": "吸附点",
    "Misc key settings": "按键杂项设置",
    "LCD Sensor Shortcuts": "LCD传感器快捷键",
    "Sticky DOF Preview": "景深预览锁定",
    "Sticky HalfShutter": "半按快门锁定",
    "Swap MENU <--> ERASE": "交换MENU <--> ERASE",
    "Swap INFO <--> PLAY": "交换INFO <--> PLAY",
    "Warning for bad settings": "错误设置警告",
    "Mode warning": "模式警告",
    "Quality warning": "画质警告",
    "WB warning": "白平衡警告",
    "Warning message": "警告消息",
    "Memory Browser": "内存浏览器",
    "HexDump": "十六进制转储",
    "Pointer dereference": "指针解引用",
    "Val hex32/int32/int16/int8/string": "值 hex32/int32/int16/int8/字符串",
    "Flashlight": "闪光灯",
    "Screenshot - 10s": "截图 - 10秒",
    "Menu screenshots": "菜单截图",
    "Spy properties": "监视属性",
    "Unmount SD card": "卸载SD卡",
    "TryPostEvent Log": "TryPostEvent日志",
    "Show tasks": "显示任务",
    "Task list": "任务列表",
    "Show CPU usage": "显示CPU使用率",
    "Show GUI events": "显示GUI事件",
    "Test GUI modes": "测试GUI模式",
    "Image buffers": "图像缓冲区",
    "Shutter Count": "快门计数",
    "Total Shutter/Mirror/Shots": "总快门/反光板/拍摄",
    "Internal Temp": "内部温度",
    "PROP Display": "属性显示",
    "Movie Logging": "视频日志",
    "Lens Info Prefs": "镜头信息设置",
    "Focus Distance Units": "对焦距离单位",
    "Name": "名称",
    "Lens ID": "镜头ID",
    "Serial num": "序列号",
    "Version": "版本",
    "Pic Quality": "画质",
    "ALO/HTP": "ALO/HTP",
    "Temperature": "温度",
    "MVI number": "MVI编号",
    "Free space": "剩余空间",
    "IS": "防抖",
    "Focus dist": "对焦距离",
    "AF/MF": "AF/MF",
    "Frames": "帧数",
    "Sequence": "序列",
    "ISO shifting": "ISO偏移",
    "Take a pic every": "拍摄间隔",
    "Start after": "开始于",
    "Stop after": "停止于",
    "LCDsensor Remote": "LCD传感器遥控",
    "Trigger level (dB)": "触发电平(dB)",
    "Trigger by": "触发方式",
    "Trigger level": "触发电平",
    "Mirror Lockup": "反光板锁定",
    "MLU mode": "MLU模式",
    "Handheld Shutter": "手持快门",
    "Handheld Delay": "手持延迟",
    "Normal MLU Delay": "正常MLU延迟",
    "Voice Tags": "语音标签",
    "Flash Tweaks": "闪光调整",
    "Flash expo comp.": "闪光曝光补偿",
    "Flash / No flash": "闪光/无闪光",
    "Shoot Preferences": "拍摄偏好",
    "Pics at once": "一次拍摄张数",
    "Use Autofocus": "使用自动对焦",
    "Post scripts": "后处理脚本",
    "Intervalometer Script": "间隔拍摄脚本",
    "Snap Simulation": "快门模拟",
    "LiveView zoom tweaks": "实时取景缩放调整",
    "Increase SharpContrast": "增强锐度对比度",
    "Zoom on HalfShutter": "半按快门缩放",
    "Zoom with Focus Ring": "对焦环缩放",
    "Zoom with old button": "旧按钮缩放",
    "WBShift G/M": "白平衡偏移 G/M",
    "WBShift B/A": "白平衡偏移 B/A",
    "ML digital ISO": "ML数字ISO",
    "ISO": "ISO",
    "HDR video": "HDR视频",
    "ISO A": "ISO A",
    "ISO B": "ISO B",
    "Optimize for": "优化目标",
    "Main Clock": "主时钟",
    "Rolling shutter": "果冻效应",
    "Sync w. Shutter": "与快门同步",
    "Ramp duration": "渐变持续时间",
    "Movie Record": "视频录制",
    "Shutter Button": "快门按钮",
    "REC key": "录制键",
    "Require long press": "需要长按",
    "MOV/MP4 time limit": "MOV/MP4时间限制",
    "Gradual Exposure": "渐变曝光",
    "Ramping speed": "渐变速度",
    "Movie Restart": "视频重启",
    "REC/STBY notify": "录制/待机通知",
    "Force LiveView": "强制实时取景",
    "Picture Style": "照片风格",
    "Sharpness strength": "锐度强度",
    "Sharpness fineness": "锐度精细度",
    "Sharpness threshold": "锐度阈值",
    "Force style for REC": "录制时强制风格",
    "Style for recording": "录制风格",
    "Pic.Style": "照片风格",
    "Powersave in LiveView": "实时取景省电",
    "Use LCD Sensor": "使用LCD传感器",
    "Use shortcut key": "使用快捷键",
    "Turn off LCD": "关闭LCD",
    "Turn off GlobalDraw": "关闭全局绘制",
    "Module info": "模块信息",
    "Modules debug": "模块调试",
    "Load modules after crash": "崩溃后加载模块",
    "Show hidden modules": "显示隐藏模块",
    "Press FUNC / PLAY": "按FUNC / PLAY",
    "Pict.Style / PLAY": "照片风格 / PLAY",
    "Press JUMP / PLAY": "按JUMP / PLAY",
    "Tap or press PLAY": "点击或按PLAY",
    "Press Av / PLAY": "按Av / PLAY",
    "Press Q / PLAY": "按Q / PLAY",
    "Joystick long-press": "摇杆长按",
    "SET / main dial": "SET / 主拨盘",
    "Zoom In": "放大",
    "Press MENU": "按MENU",
    "Key Shortcuts": "按键快捷方式",
    "Mid-range correction": "中间调校正",
    "Shutter fine-tuning": "快门微调",
    "Negative": "负片",
    "Swap U-V": "交换U-V",
    "Register family/base/offset": "寄存器族/基址/偏移",
    "Value": "值",
    "Altering mode": "修改模式",
    "Random register": "随机寄存器",
    "Video Hacks": "视频破解",
    "Movie crop mode": "视频裁切模式",
    "GPS Power Save": "GPS省电",
    "Memory patches": "内存补丁",
    "LV raw type": "LV raw类型",
    "Recovery ISO": "恢复ISO",
    "Midtone overlapping": "中间调重叠",
    "Post Deflicker": "后期去闪烁",
    "Sidecar file type": "附属文件类型",
    "Show graph": "显示图表",
    "Use in LV": "在LV中使用",
    "Lens aperture": "镜头光圈",
    "TV minimum": "TV最小值",
    "Same TV curve": "相同TV曲线",
    "ISO curve": "ISO曲线",
    "Silent Mode": "静音模式",
    "Slit-Scan Mode": "狭缝扫描模式",
    "Trigger Mode": "触发模式",
    "File Format": "文件格式",
    "Target YRES": "目标Y分辨率",
    "CMOS[2]": "CMOS[2]",
    "File Manager": "文件管理器",
    "Memory Benchmarks": "内存基准测试",
    "Misc Benchmarks": "杂项基准测试",
    "Memcpy benchmark": "Memcpy基准测试",
    "Memory benchmark": "内存基准测试",
    "Focus peaking benchmark": "峰值对焦基准测试",
    "Menu benchmark": "菜单基准测试",
    "Start Scan": "开始扫描",
    "Scan type": "扫描类型",
    "Scan passes": "扫描次数",
    "ND Strength": "ND强度",
    "Measure ND": "测量ND",
    "Image file naming": "图像文件命名",
    "Image file prefix": "图像文件前缀",
    "Image file number": "图像文件编号",
    "Image folder number": "图像文件夹编号",
    "Ramping options": "渐变选项",
    "Use Global Time": "使用全局时间",
    "Loop After": "循环于",
    "List Keyframes": "列出关键帧",
    "Save Keyframes": "保存关键帧",
    "New Keyframe...": "新建关键帧...",
    "Keyframe Time": "关键帧时间",
    "Interval Time": "间隔时间",
    "RAW video (MLV)": "RAW视频(MLV)",
    "Resolution": "分辨率",
    "Aspect Ratio": "宽高比",
    "Aspect ratio": "宽高比",
    "Bit Depth": "位深",
    "Create Directory": "创建目录",
    "Global Draw": "全局绘制",
    "Frame Skipping": "跳帧",
    "Preview Options": "预览选项",
    "Preview": "预览",
    "Status When Recording": "录制时状态",
    "Files > 4GiB (exFAT)": "文件>4GiB(exFAT)",
    "Digital Dolly": "数字移动",
    "Digital dolly": "数字移动",
    "Card Warm-up": "卡预热",
    "card warm-up": "卡预热",
    "Use SRM Job Memory": "使用SRM作业内存",
    "Use SRM memory": "使用SRM内存",
    "Extra Hacks": "额外破解",
    "Small hacks": "小破解",
    "Debug Trace": "调试跟踪",
    "Show Buffer Graph": "显示缓冲区图表",
    "Show graph": "显示图表",
    "Buffer Fill Method": "缓冲区填充方法",
    "CF-only Buffers": "仅CF缓冲区",
    "Card Spanning": "卡跨越",
    "Reserve Card Space": "预留卡空间",
    "Tag: Text": "标签:文本",
    "Tag: Take": "标签:场次",
    "RAW video": "RAW视频",
    "Data format": "数据格式",
    "Pre-record": "预录制",
    "Rec trigger": "录制触发",
    "H.264 proxy": "H.264代理",
    "Sync beep": "同步提示音",
    "Show EDMAC": "显示EDMAC",
    "Playback": "回放",
    "Sound recording": "录音",
    "Enable sound": "启用声音",
    "Sampling rate": "采样率",
    "Audio delay": "音频延迟",
    "Trace output": "跟踪输出",
    "Resolution preset": "分辨率预设",
    "Frame skip": "跳帧",
    "Single file": "单文件",
    "Self tests": "自测",
    "Stubs API test": "Stubs API测试",
    "Thread safety test": "线程安全测试",
    "SD speed autotune": "SD速度自动调优",
    "SD frequency": "SD频率",
    "SD Overclock": "SD超频",
    "Show CID info": "显示CID信息",

    # === Help Text ===
    "Change H.264 bitrate. Be careful, recording may stop!": "更改H.264码率。注意,录制可能停止!",
    "Firmware default / CBR (recommended) / VBR (very risky)": "固件默认/CBR(推荐)/VBR(高风险)",
    "1.0x = Canon default, 0.4x = 30minutes, 1.4x = fast card.": "1.0x=佳能默认,0.4x=30分钟,1.4x=高速卡",
    "Quality factor (-16 = best quality). Try not to use it!": "质量因子(-16=最佳质量)。尽量不用!",
    "A = average, B = instant bitrate, Q = instant QScale.": "A=平均,B=瞬时码率,Q=瞬时QScale",
    "ML will pause CPU-intensive graphics if buffer gets full.": "缓冲区满时ML将暂停CPU密集型图形",
    "You may get higher bitrates if you record sound separately.": "独立录音可获得更高码率",
    "Time indicator while recording.": "录制时的时间指示器",
    "Takes a picture when the subject comes in focus. MF only.": "主体对焦时拍摄。仅手动对焦",
    "Focus with arrow keys. MENU while REC = save focus point.": "用方向键对焦。录制时按MENU保存对焦点",
    "You can focus with arrow keys or with the LCD sensor": "可用方向键或LCD传感器对焦",
    "[Q]: fix here rack end point. SET+L/R: start point.": "[Q]:固定移位终点。SET+左/右:起点",
    "Press SET for rack focus, or PLAY to also start recording.": "按SET移位对焦,或按PLAY同时开始录制",
    "Takes pictures at different focus points.": "在不同对焦点拍摄",
    "Run the focus stacking sequence.": "运行焦点堆叠序列",
    "Tip: press MENU to interrupt the stacking sequence.": "提示:按MENU中断堆叠序列",
    "Number of shots in front of current focus point.": "当前对焦点前方的拍摄数",
    "On some lenses, this may be reversed.": "某些镜头可能相反",
    "Number of shots behind current focus point.": "当前对焦点后方的拍摄数",
    "Number of focus steps between two pictures.": "两张照片之间的对焦步数",
    "Seconds between stack segments to let flashes recycle.": "堆叠段之间的秒数,供闪光灯回电",
    "Sets up stack focus to use the same range as rack focus.": "设置堆叠对焦使用与移位对焦相同的范围",
    "Tuning parameters and prefs for rack/stack/follow focus.": "移位/堆叠/跟随对焦的调节参数",
    "Step size for focus commands (same units as in EOS Utility)": "对焦命令步长(与EOS Utility相同单位)",
    "Delay between two successive focus commands.": "两次对焦命令之间的延迟",
    "Wait for 'focus done' signal before sending next command.": "等待'对焦完成'信号后再发送下一条命令",
    "Focus direction for Left and Right keys.": "左/右键的对焦方向",
    "Focus direction for Up and Down keys.": "上/下键的对焦方向",
    "Number of seconds before starting focus operation.": "对焦操作开始前的秒数",
    "Settings about Depth of Field info displays.": "景深信息显示设置",
    "Circle of confusion used for DOF calculations.": "景深计算用的弥散圆",
    "Default value: 19 for APS-C and 29 for full-frame cameras.": "默认值:APS-C为19,全画幅为29",
    "Formula for computing the depth of field:": "景深计算公式:",
    "Display DOF above Focus distance, in LiveView.": "在实时取景中对焦距离上方显示景深",
    "Enable/disable ML overlay graphics (zebra, cropmarks...)": "启用/禁用ML叠加图形(斑马纹,裁切标记...)",
    "Zebra stripes: show overexposed or underexposed areas.": "斑马纹:显示过曝或欠曝区域",
    "Luma: red/blue. RGB: show color of the clipped channel(s).": "亮度:红/蓝。RGB:显示裁切通道颜色",
    "Underexposure threshold.": "欠曝阈值",
    "Overexposure threshold.": "过曝阈值",
    "You can hide zebras when recording.": "录制时可隐藏斑马纹",
    "Use RAW zebras if possible.": "尽可能使用RAW斑马纹",
    "RAW zebra underexposure threshold": "RAW斑马纹欠曝阈值",
    "(in EVs above the noise floor)": "(高于噪点下限的EV值)",
    "Show which parts of the image are in focus.": "显示图像中对焦清晰的区域",
    "Fine-tune the focus detection algorithm:": "微调对焦检测算法:",
    "How to display peaking. Alpha looks nicer, but image lags.": "峰值显示方式。Alpha更好看,但有延迟",
    "How many pixels are considered in focus (percentage).": "多少比例的像素被视为合焦(百分比)",
    "Focus peaking color (fixed or color coding).": "峰值对焦颜色(固定或颜色编码)",
    "Display LiveView image in grayscale.": "以灰度显示实时取景图像",
    "Zoom box for checking focus. Can be used while recording.": "用于检查对焦的缩放框。可在录制时使用",
    "Trigger Magic Zoom by focus ring or half-shutter.": "通过对焦环或半按快门触发魔法缩放",
    "Zoom when recording / trigger from focus ring / Zoom button": "录制时缩放/对焦环触发/缩放按钮",
    "Size of zoom box (small / medium / large / full screen).": "缩放框大小(小/中/大/全屏)",
    "Size of zoom box (small / medium / large).": "缩放框大小(小/中/大)",
    "Position of zoom box (fixed or linked to focus box).": "缩放框位置(固定或关联对焦框)",
    "1:1 displays recorded pixels, 2:1 displays them doubled.": "1:1显示原始像素,2:1显示双倍像素",
    "How to show focus confirmation (green bars / split screen).": "对焦确认显示方式(绿条/裂像)",
    "Overlay any image in LiveView. In PLAY mode, press LV btn.": "在实时取景中叠加任意图像。回放模式按LV键",
    "Update the overlay whenever you take a picture.": "每次拍摄时更新叠加图像",
    "Exposure aid: display brightness from a small spot.": "曝光辅助:显示小区域的亮度",
    "Measurement unit for brightness level(s).": "亮度级别的测量单位",
    "Spotmeter position: center or linked to focus box.": "点测光位置:中心或关联对焦框",
    "Exposure aid: each brightness level is color-coded.": "曝光辅助:每个亮度级别用颜色编码",
    "False color palettes for exposure, banding, green screen...": "曝光/条带/绿屏的伪彩色调色板",
    "Exposure aid: shows the distribution of brightness levels.": "曝光辅助:显示亮度级别分布",
    "Choose between YUV-based (JPG) or RAW-based histogram.": "选择YUV(JPG)或RAW直方图",
    "If RAW data is not available, it will fall back to YUV-based.": "RAW数据不可用时回退到YUV",
    "Choose an EV image indicator to display on the histogram.": "选择在直方图上显示的EV指示器",
    "Linear or logarithmic histogram.": "线性或对数直方图",
    "Display warning dots when one color channel is clipped.": "某颜色通道裁切时显示警告点",
    "Numbers represent the percentage of pixels clipped.": "数字表示裁切像素的百分比",
    "Exposure aid: useful for checking overall brightness.": "曝光辅助:用于检查整体亮度",
    "Waveform size: Small / Large / FullScreen.": "波形图大小:小/大/全屏",
    "Electronic level indicator in 0.5 degree steps.": "电子水平仪,0.5度步进",
    "Show the frame rate of overlay loop (zebras, peaking...)": "显示叠加循环的帧率(斑马纹,峰值...)",
    "Gain applied to both inputs in analog domain (preferred).": "模拟增益,作用于两个输入(推荐)",
    "Digital gain (not recommended, use only for headphones!)": "数字增益(不推荐,仅用于耳机!)",
    "Digital gain (LEFT). Any nonzero value reduces quality.": "数字增益(左)。任何非零值都会降低质量",
    "Digital gain (RIGHT). Any nonzero value reduces quality.": "数字增益(右)。任何非零值都会降低质量",
    "Automatic Gain Control - turn it off :)": "自动增益控制 - 建议关闭 :)",
    "Audio input: internal / external / both / balanced / auto.": "音频输入:内置/外部/两者/平衡/自动",
    "High pass filter for wind noise reduction.": "用于风噪降低的高通滤波器",
    "Needed for int. and some other mics, but lowers impedance.": "内置和某些麦克风需要,但降低阻抗",
    "Monitoring via A-V jack. Disable if you use a SD display.": "通过A-V接口监听。使用SD显示时禁用",
    "Output volume for audio monitoring (headphones only).": "音频监听输出音量(仅耳机)",
    "Config auto save, manual save, restore defaults...": "配置自动保存,手动保存,恢复默认...",
    "If you hold the SET button pressed at camera startup:": "如果开机时按住SET按钮:",
    "Choose a configuration preset.": "选择配置预设",
    "If enabled, ML settings are saved automatically at shutdown.": "启用后,ML设置在关机时自动保存",
    "Save config now": "立即保存配置",
    "Save ML settings to current preset directory.": "将ML设置保存到当前预设目录",
    "Restore ML defaults": "恢复ML默认",
    "This restores ML default settings, by deleting all CFG files.": "通过删除所有CFG文件恢复ML默认设置",
    "Auto expose to the right when you shoot RAW.": "拍摄RAW时自动向右曝光",
    "Slowest shutter speed for ETTR (longest exposure time).": "ETTR最慢快门(最长曝光时间)",
    "Exposure target for ETTR. Recommended: -0.5 or -1 EV.": "ETTR曝光目标。推荐:-0.5或-1 EV",
    "Highlight ignore": "高光忽略",
    "How many bright pixels are allowed above the target level.": "允许超过目标亮度的像素数",
    "Choose what color channels are allowed to be clipped.": "选择允许裁切的颜色通道",
    "Midtone SNR limit": "中间调信噪比限制",
    "Shadow SNR limit": "阴影信噪比限制",
    "Link to Canon shutter": "关联佳能快门",
    "Hack to adjust slowest shutter from main dial.": "从主拨盘调整最慢快门",
    "Link to Dual ISO": "关联双ISO",
    "Show metered areas": "显示测光区域",
    "Make status beeps (1 = OK, 2 = need more pictures, 3 = error).": "状态提示音(1=正常,2=需更多照片,3=错误)",
    "Show debug info": "显示调试信息",
    "For camera nerds.": "给相机极客",
    "Take pics in LiveView without moving the shutter mechanism.": "在实时取景中拍摄,不移动快门机构",
    "Choose the silent picture mode:": "选择静音拍摄模式:",
    "Choose slitscan mode:": "选择狭缝扫描模式:",
    "Choose when to capture the image:": "选择图像捕获时机:",
    "File format to save the image as:": "图像保存格式:",
    "Record RAW video. Press LiveView to start.": "录制RAW视频。按实时取景开始",
    "Save video chunks in separate folders.": "将视频分块保存到单独文件夹",
    "Disable global draw while recording for speed.": "录制时禁用全局绘制以提速",
    "Enable if you don't mind skipping frames.": "如不介意跳帧则启用",
    "Display status while recording.": "录制时显示状态",
    "Start delay. Useful to stabilize in photo mode.": "启动延迟。用于在照片模式稳定",
    "Don't split files on 4GiB margins.": "不在4GiB边界分割文件",
    "Smooth panning of the recording window.": "录制窗口平滑移动",
    "Write a large file on the card at camera startup.": "开机时在卡上写入大文件",
    "Allocate memory from SRM job buffers.": "从SRM作业缓冲区分配内存",
    "Slow down Canon GUI, lock digital expo while recording.": "录制时减慢佳能GUI,锁定数字曝光",
    "Write an execution trace. Causes performance drop.": "写入执行跟踪。会导致性能下降",
    "Displays a graph of the current buffer usage and expected frames.": "显示当前缓冲区使用和预期帧数图表",
    "Method for filling buffers. Will affect write speed.": "缓冲区填充方法。影响写入速度",
    "How many of the largest buffers are for CF writing.": "多少个大缓冲区用于CF写入",
    "Span video file over cards to use SD+CF write speed.": "跨卡分割视频以利用SD+CF写入速度",
    "Write a file to the card before recording.": "录制前在卡上写入文件",
    "Free text field.": "自由文本字段",
    "Auto-counting take number.": "自动计数场次号",
    "Record RAW video (MLV format, no sound, basic metadata).": "录制RAW视频(MLV格式,无声音,基本元数据)",
    "Press LiveView to start recording.": "按实时取景开始录制",
    "Choose the output format.": "选择输出格式",
    "Raw video preview.": "RAW视频预览",
    "Pre-records a few seconds of video into memory.": "预录几秒视频到内存",
    "Use external trigger to start/pause recording.": "使用外部触发开始/暂停录制",
    "Span video file over SD + CF cards.": "跨SD+CF卡分割视频",
    "Record a H.264 video at the same time.": "同时录制H.264视频",
    "Slow down Canon GUI, disable auto exposure, white balance.": "减慢佳能GUI,禁用自动曝光,白平衡",
    "Beeps on recording start for better sync.": "录制开始时提示音,便于同步",
    "Plots the EDMAC read/write pointers.": "绘制EDMAC读写指针",
    "Play back the last raw video clip.": "回放最后一段RAW视频",
}

# Sort longest first to avoid partial matches
KEYS = sorted(DICT.keys(), key=lambda s: -len(s))

files = glob.glob(str(ROOT / "src" / "*.c")) + glob.glob(str(ROOT / "modules" / "*" / "*.c"))

total = 0
per_file = {}

for f in files:
    p = Path(f)
    try:
        txt = p.read_text(encoding="utf-8")
    except:
        continue
    orig = txt
    nfile = 0

    for en in KEYS:
        if en not in txt:
            continue
        zh = DICT[en]
        en_e = re.escape(en)

        # 1) .name/.help/.help2 = "EN[padding]"
        for field in ("name", "help", "help2"):
            pat = re.compile(r'(\.' + field + r'\s*=\s*)"' + en_e + r'(\s*)"')
            txt, c = pat.subn(lambda m: m.group(1) + '"' + zh + m.group(2) + '"', txt)
            nfile += c

        # 2) inside .choices = (char *[]) { ... }  -- translate choice strings
        def repl_choices(m):
            global nfile
            block = m.group(0)
            inner = re.compile('"' + en_e + r'(\s*)"')
            block2, c = inner.subn(lambda mm: '"' + zh + mm.group(1) + '"', block)
            nfile += c
            return block2
        txt = re.sub(r'\.choices\s*=\s*\([^)]*\)\s*\{[^}]*\}', repl_choices, txt)

    if txt != orig:
        p.write_text(txt, encoding="utf-8")
        per_file[str(p.relative_to(ROOT))] = nfile
        total += nfile

print(f"Total replacements: {total}")
print(f"Files changed: {len(per_file)}")
for f in sorted(per_file, key=lambda k: -per_file[k])[:30]:
    print(f"  {per_file[f]:4d}  {f}")