#!/usr/bin/env python3
"""Comprehensive translation of all remaining help texts."""
from pathlib import Path
import glob

ROOT = Path(__file__).resolve().parent.parent

D = {
    "A quick test which covers basic functionality.": "覆盖基本功能的快速测试。",
    "A thorough test which randomly enables functions from menu.": "随机启用菜单功能的全面测试。",
    "A trick to allow 3rd party flashes to fire in LiveView.": "允许副厂闪光灯在实时取景中触发的技巧。",
    "ADTG 0x8178, 0x8196, 0x82F8": "ADTG 0x8178, 0x8196, 0x82F8",
    "ADTG 0x8179, 0x8197, 0x82F9": "ADTG 0x8179, 0x8197, 0x82F9",
    "AFMA scan type and range": "自动对焦微调扫描类型和范围",
    "Address to be analyzed. Press Q to select the digit to edit.": "要分析的地址。按Q选择要编辑的位。",
    "Adjust AFMA value manually. Range: -100...+100.": "手动调整自动对焦微调值。范围:-100...+100。",
    "Adjust Kelvin white balance.": "调整开尔文白平衡。",
    "Adjust and fine-tune ISO. Also displays APEX Sv value.": "调整和微调ISO。同时显示APEX Sv值。",
    "Adjust aperture. Also displays APEX aperture (Av) in stops.": "调整光圈。同时显示APEX光圈(Av)档数。",
    "Adjust color tone in current picture style.": "调整当前照片风格的色调。",
    "Adjust contrast in current picture style.": "调整当前照片风格的对比度。",
    "Adjust dark level, as with 'dcraw -k'. Fixes green shadows.": "调整暗电平,类似'dcraw -k'。修复绿色偏暗。",
    "Adjust saturation in current picture style.": "调整当前照片风格的饱和度。",
    "Adjust sharpness fineness in current picture style.": "调整当前照片风格的锐度精细度。",
    "Adjust sharpness in current picture style.": "调整当前照片风格的锐度。",
    "Adjust sharpness strength in current picture style.": "调整当前照片风格的锐度强度。",
    "Adjust sharpness threshold in current picture style.": "调整当前照片风格的锐度阈值。",
    "Advanced intervalometer ramping options.": "高级间隔拍摄过渡选项。",
    "Advanced: WBShift, RGB multipliers, Push-button WB...": "高级:白平衡偏移、RGB乘数、一键白平衡...",
    "Advanced: digital ISO tweaks, HTP, ISO 50, ISO 800.000...": "高级:数字ISO微调、HTP、ISO 50、ISO 800.000...",
    "After release you previos exposure will be restored.": "释放后将恢复之前的曝光设置。",
    "After running this a few times, you'll get ERR70.": "运行几次后会出现ERR70错误。",
    "After running this a few times, you'll run out of memory.": "运行几次后内存将耗尽。",
    "Allocate and free a large block of RAM (16 MB); repeat 1000 times.": "分配和释放大块RAM(16MB);重复1000次。",
    "Allocate up to 50000 small blocks, 32K each, until memory gets full.": "分配最多50000个小块,每个32K,直到内存满。",
    "Allocates 1MB RAM from any source, without freeing it.": "从任意来源分配1MB RAM,不释放。",
    "Allocates 1MB RAM using AllocateMemory, without freeing it.": "用AllocateMemory分配1MB RAM,不释放。",
    "Also up/down keys/joystick work as +/- rating if zoomed out.": "缩小时上/下键/摇杆也可用作+/-评分。",
    "Alternate ISO for every 2 sensor scan lines.": "每2行传感器扫描线交替ISO。",
    "Alternates ISO between frames. Flickers while recording.": "帧间交替ISO。录制时会闪烁。",
    "Always ON: just the Canon mode, press shutter twice.\n": "始终开启:仅佳能模式,按两次快门。\n",
    "Always ON: when you take a pic, or continuously in LiveView\n": "始终开启:拍照时,或在实时取景中持续\n",
    "Always use LiveView (with manual lens or after lens swap).": "始终使用实时取景(手动镜头或换镜头后)。",
    "Ambient light from the sensor under LCD, in raw units.": "LCD下方传感器的环境光,原始单位。",
    "Analog ISO component (ISO at which the sensor is driven).": "模拟ISO分量(传感器驱动ISO)。",
    "Analog mic boost.": "模拟麦克风增强。",
    "Anything still running after that would be secondary CPUs or hardware.": "之后仍在运行的将是副CPU或硬件。",
    "Audio input: internal / external / both / auto.": "音频输入:内置/外部/两者/自动。",
    "Auto Load Config at Start and/or Override BR/InitQP": "启动时自动加载配置和/或覆盖BR/InitQP",
    "Auto calibrate AF microadjustment ( youtu.be/7zE50jCUPhM )": "自动校准自动对焦微调( youtu.be/7zE50jCUPhM )",
    "Auto compensate minimum ISO & minimum AV & EC changes.": "自动补偿最小ISO、最小光圈和曝光补偿变化。",
    "Auto-restart movie recording, if it happens to stop.": "录制停止时自动重新开始录制。",
    "Automatic exposure algorithm based on predefined curves.": "基于预定义曲线的自动曝光算法。",
    "BLUE channel multiplier, for custom white balance.": "蓝色通道乘数,用于自定义白平衡。",
    "Balance fine texture details vs strong high-contrast edges.": "平衡精细纹理细节与强高对比度边缘。",
    "Bar peak decay, -40...0 dB, yellow at -12 dB, red at -3 dB.": "条形峰值衰减,-40...0 dB,-12 dB变黄,-3 dB变红。",
    "Battery remaining. Wait for 2% discharge before reading.": "剩余电量。等待2%放电后再读取。",
    "Be careful :)": "请小心 :)",
    "Be careful, won't take pics if it can't autofocus.": "注意,无法自动对焦时不会拍摄。",
    "Before running, focus manually on a test target in LiveView.": "运行前,在实时取景中手动对焦到测试目标。",
    "Benchmarks for focus peaking and menu backend (for now)": "峰值对焦和菜单后端基准测试(目前)",
    "Bitrate settings": "码率设置",
    "Block shutter button while recording (avoids ERR99)": "录制时锁定快门按钮(避免ERR99)",
    "Blocks get encrypted with the same 64 bit key. The smaller the more secure but slower.": "块用相同64位密钥加密。越小越安全但越慢。",
    "Blue-Amber WBShift; 1 unit = 5 mireks on Kelvin axis.": "蓝-琥珀白平衡偏移;1单位=开尔文轴上5 mireks。",
    "Btw: Real focus patterns aren't working on 6D (yet?).": "顺便说:真正的对焦模式在6D上还不工作(?)。",
    "CF card info: make and model.": "CF卡信息:品牌和型号。",
    "CF or SD card benchmarks": "CF或SD卡基准测试",
    "CID register contains some information about an SD card.": "CID寄存器包含SD卡的一些信息。",
    "CRC7 checksum.": "CRC7校验和。",
    "Calls DisableBootDisk EvProc": "调用DisableBootDisk EvProc",
    "Calls EnableBootDisk EvProc": "调用EnableBootDisk EvProc",
    "Can be absolute or relative to primary ISO from Canon menu.": "可以是绝对值或相对于佳能菜单主ISO的值。",
    "Can select between Metric and Imperial focus distance units": "可选择公制或英制对焦距离单位",
    "Canon's digital ISO component. Strongly recommended: 0.": "佳能数字ISO分量。强烈推荐:0。",
    "Cartoonish look obtained by emphasizing the edges.": "通过强调边缘获得的卡通效果。",
    "Causes excessive redraws for testing the graphics backend": "导致过度重绘以测试图形后端",
    "Causes intentionally wrong behavior to see DryOS reaction.": "故意导致错误行为以观察DryOS反应。",
    "Change 29:59 movie recording limit": "更改29:59视频录制限制",
    "Change H.264 bitrate. Pick configs. Be careful, recording may stop!": "更改H.264码率。选择配置。注意,录制可能停止!",
    "Change camera bootflag status": "更改相机启动标志状态",
    "Change current picture style.": "更改当前照片风格。",
    "Change file prefix for dual ISO photos (e.g. DUAL0001.CR2).": "更改双ISO照片文件前缀(如DUAL0001.CR2)。",
    "Changes FPS. Also disables sound and alters shutter speeds.": "更改FPS。同时禁用声音并改变快门速度。",
    "Changes a DIGIC register to find out what it does. DANGER!": "更改DIGIC寄存器以了解其功能。危险!",
    "Changes address to *(int*)addr [SET] or goes back [PLAY].": "将地址改为*(int*)addr [SET]或返回 [PLAY]。",
    "Changes duration of the bulb timer": "更改B门计时器持续时间",
    "Changes the Kelvin white balance": "更改开尔文白平衡",
    "Changes the interval between shots": "更改拍摄间隔",
    "Changing FPS has side effects - choose what's best for you:": "更改FPS有副作用 - 选择最适合的:",
    "Check card read/write speed with a 16MB buffer. Uses a 1GB temp file.": "用16MB缓冲区检查卡读写速度。使用1GB临时文件。",
    "Check how fast is your camera. Card, CPU, graphics...": "检查相机速度。卡、CPU、图形...",
    "Check how fast peaking runs in PLAY mode (1000 iterations).": "检查回放模式峰值对焦速度(1000次迭代)。",
    "Check memcpy speed using different subsystems.": "用不同子系统检查memcpy速度。",
    "Check memory read/write speed using different methods.": "用不同方法检查内存读写速度。",
    "Check speed of menu backend.": "检查菜单后端速度。",
    "Checks various buffer sizes. You don't need it for raw video benchmarks,": "检查各种缓冲区大小。RAW视频基准测试不需要,",
    "Choose af points directly, display OFF, arrows+SET.": "直接选择对焦点,关闭显示,方向键+SET。",
    "Choose an option, restart the camera to apply.": "选择选项,重启相机以应用。",
    "Choose functions for arrows keys. Toggle w.": "选择方向键功能。切换方式",
    "Choose how to start the focus stacking sequence.": "选择如何开始焦点合成序列。",
    "Choose mode :Notch,EQ,Notch/EQ,Enhance [12],Loudness.": "选择模式:Notch,EQ,Notch/EQ,Enhance [12],Loudness。",
    "Choose patterns outside ML menu, display OFF, arrows+SET.": "在ML菜单外选择模式,关闭显示,方向键+SET。",
    "Choose the available shutter speed range:": "选择可用快门速度范围:",
    "Choose the behavior of SET key in ML menu:": "选择ML菜单中SET键的行为:",
    "Choose what type of raw stream we should use in LiveView.": "选择实时取景中使用的RAW流类型。",
    "Chose the action type to perform when triggered.": "选择触发时执行的操作类型。",
    "Clear screen when you hold shutter halfway or when idle.": "半按快门或空闲时清除屏幕。",
    "Clears all keyframes.": "清除所有关键帧。",
    "Click to select some random register.": "点击选择随机寄存器。",
    "Color scheme for bitmap overlays (ML menus, Canon menus...)": "位图叠加的配色方案(ML菜单、佳能菜单...)",
    "Color space for histogram: Luma channel (YUV) / RGB.": "直方图色彩空间:亮度通道(YUV)/RGB。",
    "Config Loaded. Disabling may keep some of the parameters": "配置已加载。禁用可能保留部分参数",
    "Configure ML beeps and play test tones (440Hz, 1kHz...)": "配置ML提示音并播放测试音(440Hz, 1kHz...)",
    "Contrast detection method. 2: more accurate, 1: less noisy.": "对比度检测方法。2:更精确,1:噪声更小。",
    "Correction applied between central area and corners.": "中央区域和边角之间应用的校正。",
    "Correction with a stronger bias towards corners.": "偏向边角的更强校正。",
    "Crazy color effects that may help with white balance.": "可能有助于白平衡的疯狂色彩效果。",
    "Create a new keyframe from the current camera settings": "从当前相机设置创建新关键帧",
    "Create sidecar files with exposure compensation,": "创建带曝光补偿的附属文件,",
    "Creates a task which will become stuck in an infinite loop.": "创建一个会陷入死循环的任务。",
    "Creates a task which will clear the interrupts and execute while(1).": "创建一个会清除中断并执行while(1)的任务。",
    "Cropmarks are mostly used in movie mode.": "裁切标记主要用于视频模式。",
    "Cropmarks or custom grids for framing.": "裁切标记或自定义构图网格。",
    "Current value of selected register. Change w. HalfShutter.": "所选寄存器的当前值。半按快门更改。",
    "Custom AF patterns (photo mode only). Ported from 400plus.": "自定义对焦模式(仅照片模式)。从400plus移植。",
    "Custom REC/STANDBY notifications, visual or audible": "自定义录制/待机通知,视觉或声音",
    "Custom image file number (e.g. IMG_1234.JPG -> IMG_5678.JPG).": "自定义图像文件编号(如IMG_1234.JPG -> IMG_5678.JPG)。",
    "Custom image file prefix (e.g. IMG_1234.JPG -> ABCD1234.JPG).": "自定义图像文件前缀(如IMG_1234.JPG -> ABCD1234.JPG)。",
    "Custom image folder num. You must take a picture to apply this setting.": "自定义图像文件夹号。需拍摄一张照片以应用此设置。",
    "Customize image file naming for still pictures. Experimental.": "自定义静态图像文件命名。实验性功能。",
    "Cycle through all GUI modes and take screenshots.": "循环所有GUI模式并截图。",
    "DCIM/100CANON/IMG_1234.JPG -> DCIM/123CANON/IMG_1234.JPG": "DCIM/100CANON/IMG_1234.JPG -> DCIM/123CANON/IMG_1234.JPG",
    "DIGIC register address, mask=000000FC.": "DIGIC寄存器地址,掩码=000000FC。",
    "DIGIC register address, mask=0000FF00.": "DIGIC寄存器地址,掩码=0000FF00。",
    "DIGIC register address, mask=FFFF0000.": "DIGIC寄存器地址,掩码=FFFF0000。",
    "DNG is slow, but needs no extra post-processing.\n": "DNG较慢,但无需额外后期处理。\n",
    "Darken sharp edges in bright areas.": "亮部锐利边缘变暗。",
    "Decrease if you get corrupted frames (dial the desired resolution here).": "出现损坏帧时减小(在此调整所需分辨率)。",
    "Decrease if you get strange colors as you move the camera.": "移动相机时出现异常颜色则减小。",
    "Delete files quickly with SET+Erase (be careful!!!)": "用SET+删除键快速删除文件(小心!!!)",
    "Delete files quickly with fewer keystrokes (be careful!!!)": "用更少按键快速删除文件(小心!!!)",
    "Delete menu settings. Reboot to take effect.": "删除菜单设置。重启生效。",
    "Desired vertical resolution (only for presets with higher resolution).": "所需垂直分辨率(仅用于更高分辨率的预设)。",
    "Detect RAM cache size by benchmarking (look for a sharp speed drop).": "通过基准测试检测RAM缓存大小(寻找速度骤降)。",
    "Detect ROM cache size by benchmarking (look for a sharp speed drop).": "通过基准测试检测ROM缓存大小(寻找速度骤降)。",
    "Diagnostic options for modules.": "模块诊断选项。",
    "Dialog templates (up/dn) and color palettes (left/right)": "对话框模板(上/下)和调色板(左/右)",
    "Digital Volume and R-L gain": "数字音量和左右声道增益",
    "Dim LCD display in LiveView when idle, to save power.": "空闲时调暗实时取景LCD显示以省电。",
    "Disable sharpening completely (below Canon's zero level).": "完全禁用锐化(低于佳能零电平)。",
    "Disable the internal GPS at power off to save power.": "关机时禁用内置GPS以省电。",
    "Display + LiveView orientation: Normal / Reverse / Mirror.": "显示+实时取景方向:正常/反转/镜像。",
    "Display GUI events (button codes).": "显示GUI事件(按键代码)。",
    "Display a test pattern to see the color palette.": "显示测试图案以查看调色板。",
    "Display memory contents in real-time (hexdump).": "实时显示内存内容(十六进制转储)。",
    "Display the 35mm equiv. focal length including crop factor.": "显示含裁切系数的35mm等效焦距。",
    "Display the contents of the selected script.": "显示所选脚本内容。",
    "Display the image buffer sizes (LiveView and Craw).": "显示图像缓冲区大小(实时取景和Craw)。",
    "Display the image in grayscale.": "以灰度显示图像。",
    "Display total CPU usage (percentage).": "显示总CPU使用率(百分比)。",
    "Displays overlay graphics upside-down and flips arrow keys.": "上下颠倒显示叠加图形并翻转方向键。",
    "Displays raw contrast image (grayscale).": "显示原始对比度图像(灰度)。",
    "Displays the tasks started by Canon and Magic Lantern.": "显示佳能和ML启动的任务。",
    "Do not load ML if you start the camera with SET pressed (default)\n": "按住SET开机时不加载ML(默认)\n",
    "Do this ONCE at HOME and then store /priv.key on your PC safely.": "在家做一次,然后将/priv.key安全存储在电脑上。",
    "Drop that amount of lines on top and bottom each": "在顶部和底部各丢弃这么多行",
    "Dummy variables with various edit ranges.": "具有不同编辑范围的虚拟变量。",
    "Dump all image buffers (LV, HD, RAW) from current video mode.": "转储当前视频模式的所有图像缓冲区(LV, HD, RAW)。",
    "Duration of FPS ramping (in real-time, not in playback).": "FPS过渡持续时间(实时,非回放)。",
    "EFIC chip temperature (raw values).": "EFIC芯片温度(原始值)。",
    "EFIC chip temperature (somewhere on the mainboard).": "EFIC芯片温度(主板上某处)。",
    "EV below overexposure.": "低于过曝的EV值。",
    "EXP: reacts to exposure changes (large movements).\n": "曝光:响应曝光变化(大幅移动)。\n",
    "Edit ISO settings.": "编辑ISO设置。",
    "Edit ISO/Shutter settings.": "编辑ISO/快门设置。",
    "Edit Shutter settings.": "编辑快门设置。",
    "Either use a key combination and/or just an easier single keystroke.": "使用组合键和/或更简单的单键。",
    "Emphasizes camera shake on LiveView display.": "在实时取景中强调相机抖动。",
    "Enable advanced intervalometer ramping": "启用高级间隔拍摄过渡",
    "Enable beep signal for misc events in ML.": "为ML各种事件启用提示音。",
    "Enable boundary display for all elements.": "为所有元素启用边界显示。",
    "Enable movie recording on 50D :)": "在50D上启用视频录制 :)",
    "Enable to override active picture style while recording.": "录制时覆盖当前照片风格。",
    "Enables 600D movie crop-mode": "启用600D视频裁切模式",
    "Enables functions for SET when you use arrow shortcuts.": "使用方向键快捷方式时启用SET功能。",
    "End scanline (very rough). Increase if white bar at bottom.": "结束扫描线(很粗糙)。底部有白条时增大。",
    "Enter editing screen.": "进入编辑界面。",
    "Enter/guess approximate strength above before beginning": "开始前输入/估算上方的大约强度",
    "Exact FPS (computed). For fine tuning, change timer values.": "精确FPS(计算值)。微调请更改定时器值。",
    "Examples: IMG_1234.JPG -> ABCD1234.JPG, IMG_1234.JPG -> IMG_0001.JPG.": "例如:IMG_1234.JPG -> ABCD1234.JPG, IMG_1234.JPG -> IMG_0001.JPG。",
    "Execute the selected script.": "执行所选脚本。",
    "Experiment for finding optimal write buffer sizes.": "寻找最佳写入缓冲区大小的实验。",
    "Experimental hacks: flush rate, GOP size. Be careful!": "实验性破解:刷新率、GOP大小。小心!",
    "Experimental image filters found by digging into DIGIC.": "通过研究DIGIC发现的实验性图像滤镜。",
    "Expo bracket. M: changes shutter. Others: changes AEcomp.\n": "曝光包围。M档:改快门。其他:改曝光补偿。\n",
    "Exposure compensation.": "曝光补偿。",
    "Exposure simulation (LiveView display type).": "曝光模拟(实时取景显示类型)。",
    "Exposure simulation.": "曝光模拟。",
    "Extended ISO/Shutter settings.": "扩展ISO/快门设置。",
    "FPS value for recording. Video will play back at Canon FPS.": "录制FPS值。视频以佳能FPS回放。",
    "Faster zoom in Play mode, for pixel peeping :)": "回放模式更快缩放,用于像素级查看 :)",
    "File write test. Some cards may have compatibility issues.": "文件写入测试。某些卡可能有兼容性问题。",
    "Fine-tune shutter speed in approx 20-microsecond increments.": "以约20微秒为步长微调快门速度。",
    "Fine-tune shutter value. Displays APEX Tv or degrees equiv.": "微调快门值。显示APEX Tv或等效角度。",
    "Fixme: this will lock up if you change the video mode during the test.": "注意:测试中更改视频模式会死机。",
    "Flood master with RPC requests and print delay.": "向主设备发送大量RPC请求并打印延迟。",
    "Flush movie buffer every n frames.": "每n帧刷新视频缓冲区。",
    "For LiveView preview only. Does not affect recording.\n": "仅用于实时取景预览,不影响录制。\n",
    "For intervalometer, motion detect, trap focus, audio remote.": "用于间隔拍摄、运动检测、陷阱对焦、声控遥控。",
    "For playback, go to Audio -> Sound Recorder.": "回放请到音频->录音器。",
    "For preview only - adjust display saturation.": "仅预览 - 调整显示饱和度。",
    "For raw video, you want to run it either in movie mode or in PLAY mode.": "RAW视频建议在视频模式或回放模式运行。",
    "For troubleshooting.": "用于排障。",
    "Force low resolution (720x480) on HDMI displays.": "在HDMI显示上强制低分辨率(720x480)。",
    "Free memory available as stack space for user tasks.": "可用作用户任务栈空间的空闲内存。",
    "Free memory from SRM_AllocateMemoryResourceFor1stJob.": "SRM_AllocateMemoryResourceFor1stJob的空闲内存。",
    "Free memory, shared between ML and Canon firmware.": "ML和佳能固件共享的空闲内存。",
    "Freezes main GUI task. Camera will stop reacting to buttons.": "冻结主GUI任务。相机将不响应按键。",
    "Frequency for ML beep and test tones (Hz).": "ML提示音和测试音频率(Hz)。",
    "GREEN channel multiplier, for custom white balance.": "绿色通道乘数,用于自定义白平衡。",
    "Gain applied to both inputs in analog domain.": "模拟域增益,作用于两个输入。",
    "Go to My Menu every time you open ML menu.": "每次打开ML菜单时进入我的菜单。",
    "Grayscale recording. Use WB or pic styles for fine tuning.": "灰度录制。用白平衡或照片风格微调。",
    "Green-Magenta white balance shift, for fluorescent lights.": "绿-品红白平衡偏移,用于荧光灯。",
    "H.264 bitrate. One unit = 10 mb/s.": "H.264码率。1单位=10 mb/s。",
    "H.264 bitrate. One unit = 10 mb/s. 0 = Off": "H.264码率。1单位=10 mb/s。0=关闭",
    "High pass filter for wind noise reduction. ML26121A.pdf p77": "风噪降低高通滤波器。ML26121A.pdf p77",
    "High values = lower FPS, more jello effect, faster shutter.": "高值=更低FPS,更多果冻效应,更快快门。",
    "High values = lower FPS, shutter speed converges to 1/fps.": "高值=更低FPS,快门速度趋近1/fps。",
    "Highlights/shadows will be half res, with aliasing/moire.": "高光/阴影为半分辨率,有锯齿/摩尔纹。",
    "Histogram [SET] and Waveform [Q] for evaluating exposure.": "直方图[SET]和波形图[Q]用于评估曝光。",
    "Hold SET to take a bulb exposure based on current expo settings": "按住SET以当前曝光设置进行B门曝光",
    "Horizontal position / binning.": "水平位置/像素合并。",
    "How fast the exposure transitions should be.": "曝光过渡的速度。",
    "How many pictures to take when the subject comes in focus.": "主体合焦时拍摄多少张照片。",
    "How to change current value [HalfShutter]. MF(+) / AF(-).": "如何更改当前值[半按快门]。手动(+) / 自动(-)。",
    "However some SD cards prefer SDR50 for high frequencies.": "但某些SD卡在高频时偏好SDR50。",
    "ISO equivalent (analog + digital components).": "等效ISO(模拟+数字分量)。",
    "ISO for half of the scanlines (usually to recover shadows).": "半数扫描线的ISO(通常用于恢复暗部)。",
    "ISO tweaks. Negative gain has better highlight roll-off.": "ISO微调。负增益有更好的高光过渡。",
    "ISO value for one half of the frames.": "一半帧的ISO值。",
    "ISO value for the other half of the frames.": "另一半帧的ISO值。",
    "If ON, you have to hold half-shutter pressed for 1 second.": "开启时需半按快门1秒。",
    "If modules have .hid files, show them anyway. Requires restart.": "如模块有.hid文件则始终显示。需重启。",
    "If not loading a config MUST set InitQP": "不加载配置时必须设置InitQP",
    "In M mode, adjust Tv/Av/ISO without changing exposure.": "M档中调整快门/光圈/ISO而不改变曝光。",
    "Include current Aperture in Keyframe": "在关键帧中包含当前光圈",
    "Include current ISO in Keyframe": "在关键帧中包含当前ISO",
    "Include current Shutter in Keyframe": "在关键帧中包含当前快门",
    "Increase LiveView saturation when adjusting white balance.": "调整白平衡时提高实时取景饱和度。",
    "Init QP - Lower is better. 0 = Off": "初始QP - 越低越好。0=关闭",
    "It may change the way you use M mode. Maybe I'm just crazy.": "可能改变你使用M档的方式。也许我疯了。",
    "Keep console shown after modules were loaded": "模块加载后保持控制台显示",
    "Keep the same exposure (brightness) as with default FPS.": "保持与默认FPS相同的曝光(亮度)。",
    "Key size when creating a RSA key pair. The smaller, the less security you have.": "创建RSA密钥对时的密钥大小。越小安全性越低。",
    "LED will blink every 10s. WARNING: this limit is there for good reason!": "LED每10秒闪烁。警告:此限制有充分理由!",
    "LEFT/RIGHT: ISO. UP/DN: Kelvin white balance. SET: PushWB.": "左/右:ISO。上/下:开尔文白平衡。SET:一键白平衡。",
    "LEFT/RIGHT: LCD bright. UP/DN: LCD saturation. SET: reset.": "左/右:LCD亮度。上/下:LCD饱和度。SET:重置。",
    "LEFT/RIGHT: Shutter. UP/DN: Aperture.  SET: 180d shutter.": "左/右:快门。上/下:光圈。SET:180度快门。",
    "LEFT/RIGHT: input gain. UP/DOWN: output gain. SET: Input.": "左/右:输入增益。上/下:输出增益。SET:输入。",
    "LUT for increasing contrast in the zoom box.": "提高缩放框对比度的LUT。",
    "Largest contiguous block from shoot memory.": "拍摄内存中最大的连续块。",
    "Largest fragmented block from shoot memory.": "拍摄内存中最大的碎片块。",
    "Let ETTR change DualISO settings so you get the SNR values": "让ETTR更改双ISO设置以获得信噪比值",
    "Lists all keyframes": "列出所有关键帧",
    "LiveView: adjust Green-Magenta once for the current scene.": "实时取景:为当前场景调整绿-品红一次。",
    "LiveView: adjust Kelvin and G-M once (Push-button WB).": "实时取景:调整开尔文和G-M一次(一键白平衡)。",
    "LiveView: adjust Kelvin value once for the current scene.": "实时取景:为当前场景调整开尔文值一次。",
    "Load modules even after camera crashed and you took battery out.": "相机崩溃并取出电池后仍加载模块。",
    "Load this script in the text editor (EDITOR.LUA).": "在文本编辑器中加载此脚本(EDITOR.LUA)。",
    "Lock shutter value in movie mode (change from Expo only).": "视频模式锁定快门值(仅从曝光菜单更改)。",
    "Log DebugMessages": "记录调试消息",
    "Log TryPostEvents": "记录TryPostEvents",
    "Loops keyframe sequence after x frames": "x帧后循环关键帧序列",
    "Low priority tasks (prio >= 0x1A) will no longer be able to run.": "= 0x1A)将无法运行。",
    "Low-level manual exposure controls (bypasses Canon limits).": "底层手动曝光控制(绕过佳能限制)。",
    "Luma: red/blue. RGB: color is reverse of clipped channel.": "亮度:红/蓝。RGB:颜色为溢出通道的反色。",
    "ML should save a crash log about 0xBAADBAAD and should not crash.": "ML应保存关于0xBAADBAAD的崩溃日志且不应崩溃。",
    "MLU delay used with intervalometer, bracketing etc.": "间隔拍摄、包围等使用的反光板锁定延迟。",
    "MLU tricks: hand-held or self-timer modes.": "反光板锁定技巧:手持或自拍模式。",
    "Main dial changes curve offset. Left & right sets EV steps per BV.": "主拨盘更改曲线偏移。左/右设置每BV的EV步数。",
    "Make sure that it corresponds to your extended ISO settings.": "确保与扩展ISO设置一致。",
    "Make sure your preferred card is selected at startup.": "确保启动时选择了首选卡。",
    "Manual Load Config from selection": "从选择手动加载配置",
    "Manufacture Date Code.": "制造日期代码。",
    "Manufacturer ID.": "制造商ID。",
    "Maximum value for Auto ISO in movie mode.": "视频模式自动ISO最大值。",
    "May help pushing the resolution a little. Start with small increments.": "可能有助于稍微提高分辨率。从小增量开始。",
    "May make the image easier to see from difficult angles.": "可能使图像在困难角度更容易看清。",
    "Measure the strength of an ND filter": "测量ND滤镜强度",
    "Memory or cache benchmarks": "内存或缓存基准测试",
    "Memory reserved statically at startup for ML binary.": "启动时为ML二进制静态保留的内存。",
    "Might conflict with Dual ISO prefixes (to be tested).": "可能与双ISO前缀冲突(待测试)。",
    "Minimum value for Auto ISO in movie mode.": "视频模式自动ISO最小值。",
    "Movie Restart, Movie Logging, REC/Standby Notify...": "录制重启、视频日志、录制/待机通知...",
    "Movie: DISP + Zoom In toggles between 1x and 3x modes.": "视频:DISP+放大在1x和3x模式间切换。",
    "Negative image. Inverts all colors :)": "负片。反转所有颜色 :)",
    "No further writes will be performed on your card from the camera.": "相机不会再对卡进行任何写入。",
    "Note: this will not remove the saved sequence.": "注意:这不会删除已保存的序列。",
    "Num. of LV display presets. Switch with": "实时取景显示预设数量。用",
    "Number of ISO/Shutter settings.": "ISO/快门设置数量。",
    "Number of mechanical shutter actions (incl. sensor cleaning)": "机械快门动作次数(含传感器清洁)",
    "Number of mirror move actions (DSLR, 0 on mirrorless)": "反光板动作次数(单反,无反为0)",
    "Number of photos made. Incl. silent (electronic) shots": "拍摄照片数。含静音(电子)拍摄",
    "Number of pics taken + number of LiveView actuations": "拍摄张数+实时取景驱动次数",
    "Number of shutter actions. Open submenu to learn more.": "快门动作次数。打开子菜单了解更多。",
    "Number of time to check for focus confirmation.": "检查合焦确认的次数。",
    "OEM/Application ID.": "OEM/应用ID。",
    "Only used if you start bracketing by pressing the shutter.": "仅用于按快门启动包围曝光时。",
    "Options for PLAY (image review) mode.": "回放(图像查看)模式选项。",
    "Options for reducing power consumption during idle times.": "减少空闲时功耗的选项。",
    "Original: default range used by Canon in selected video mode.\n": "原始:佳能在所选视频模式使用的默认范围。\n",
    "Other ML features may use the options below (e.g. intervalometer in LV).": "其他ML功能可能使用以下选项(如LV中的间隔拍摄)。",
    "Override audio setting by ML": "ML覆盖音频设置",
    "Overriding dynamic configs will result in fixed QP": "覆盖动态配置将导致固定QP",
    "PLAY: quick start.": "回放:快速开始。",
    "Percentage of overall brightness level.\n": "整体亮度百分比。\n",
    "Performs some math operations which will divide by zero.": "执行一些除以零的数学运算。",
    "Pickbox: SET shows a list of choices, select and confirm.\n": "选择框:SET显示选项列表,选择并确认。\n",
    "Place your scripts under ML/SCRIPTS directory.": "将脚本放在ML/SCRIPTS目录下。",
    "Play a 5-second test tone with current settings.": "用当前设置播放5秒测试音。",
    "Play a short beep which will be used for ML events.": "播放ML事件用的短提示音。",
    "Play back a WAV file, in built-in speaker or headphones.": "在内置扬声器或耳机中回放WAV文件。",
    "Position of top/bottom bars, useful for external displays.": "上/下条位置,用于外接显示器。",
    "Powersave always works during standby; optionally also while recording.": "待机时省电始终有效;录制时可选。",
    "Preferences related to SD/CF card operation.": "SD/CF卡相关偏好设置。",
    "Press SET for detailed info.": "按SET查看详细信息。",
    "Press SET to load/run this script.": "按SET加载/运行此脚本。",
    "Press SET to start or stop recording.": "按SET开始或停止录制。",
    "Prevent Canon firmware from turning off LiveView after 30 minutes.": "防止佳能固件30分钟后关闭实时取景。",
    "Prevents display mirroring, which may reverse ML texts.": "防止显示镜像,否则可能反转ML文字。",
    "Product Name.": "产品名称。",
    "Product Revision.": "产品版本。",
    "Quickly toggle between two expo presets (ISO,Tv,Av,Kelvin).": "在两个曝光预设间快速切换(ISO,快门,光圈,开尔文)。",
    "RED channel multiplier, for custom white balance.": "红色通道乘数,用于自定义白平衡。",
    "ROM0.BIN:      NA, ROM1.BIN:FE000000, RAM4.BIN": "ROM0.BIN:      NA, ROM1.BIN:FE000000, RAM4.BIN",
    "ROM0.BIN:E0000000, ROM1.BIN:F0000000, RAM4.BIN": "ROM0.BIN:E0000000, ROM1.BIN:F0000000, RAM4.BIN",
    "ROM0.BIN:F0000000, ROM1.BIN:F8000000, RAM4.BIN": "ROM0.BIN:F0000000, ROM1.BIN:F8000000, RAM4.BIN",
    "Ramp between overridden FPS and default FPS. Undercrank only.": "在覆盖FPS和默认FPS间过渡。仅欠速。",
    "Raw property display (read-only)": "原始属性显示(只读)",
    "Read the contents of CID register.": "读取CID寄存器内容。",
    "Read-only.": "只读。",
    "Read-only. Lenses from different manufacturers may have the same ID.": "只读。不同厂商镜头可能有相同ID。",
    "Read-only. Should match exiftool TEST.CR2 -LensSerialNumber .": "只读。应与exiftool TEST.CR2 -LensSerialNumber匹配。",
    "Read-only. Zoom lenses are only updated in LiveView.": "只读。变焦镜头仅在实时取景中更新。",
    "Record 14-bit RAW video of lightning bolts.": "录制14-bit RAW闪电视频。",
    "Record Digital Volume.": "录制数字音量。",
    "Record RAW data instead of YUV422 (no decoder yet)": "录制RAW数据而非YUV422(尚无解码器)",
    "Record and playback short audio clips (WAV).": "录制和回放短音频片段(WAV)。",
    "Record audio with WAV separately.": "独立录制WAV音频。",
    "Record audio with WAV separately. Source will auto select.": "独立录制WAV音频。音源自动选择。",
    "Record every n-th frame": "每n帧录制一帧",
    "Record into one single file (it is faster)": "录制成单个文件(更快)",
    "Remember last Zoom position in playback mode.": "回放模式记忆上次缩放位置。",
    "Rename 422 files to MP4 (trick for EyeFi cards).": "将422文件重命名为MP4(EyeFi卡技巧)。",
    "Rename CR2 files to AVI (trick for EyeFi cards).": "将CR2文件重命名为AVI(EyeFi卡技巧)。",
    "Rename back AVI files to CR2 (trick for EyeFi cards).": "将AVI文件重命名回CR2(EyeFi卡技巧)。",
    "Rename back MP4 files to 422 (trick for EyeFi cards).": "将MP4文件重命名回422(EyeFi卡技巧)。",
    "Reset menu settings": "重置菜单设置",
    "Results saved in BENCH.LOG.": "结果保存在BENCH.LOG。",
    "Run C scripts with TinyCC, http://bellard.org/tcc/.": "用TinyCC运行C脚本,http://bellard.org/tcc/。",
    "Run Canon's SD autotune. You can benchmark to check improvement": "运行佳能SD自动调优。可基准测试检查改善",
    "Run before uploading files to a Wi-Fi card, to avoid data corruption.": "上传到Wi-Fi卡前运行,避免数据损坏。",
    "Run small C-like scripts. http://code.google.com/p/picoc/": "运行小型类C脚本。http://code.google.com/p/picoc/",
    "SD bus clock. Applied at module load; restart to take effect": "SD总线时钟。模块加载时应用;重启生效",
    "SDR104 mode may be required for >100 MHz. It's ON by default.": ">100 MHz可能需要SDR104模式。默认开启。",
    "Save current keyframes to file.": "将当前关键帧保存到文件。",
    "Save menu settings": "保存菜单设置",
    "Save metadata for each movie, e.g. MVI_1234.LOG": "为每个视频保存元数据,如MVI_1234.LOG",
    "Saves the contents of DIGIC shadow copy to DIGIC.LOG.": "将DIGIC影子副本内容保存到DIGIC.LOG。",
    "Scaling for input signal (useful with flat picture styles).": "输入信号缩放(适用于平面照片风格)。",
    "Scan from top to bottom as picture is taken.\n": "拍摄时从上到下扫描。\n",
    "Screen will be captured when you leave this menu.": "离开此菜单时将截屏。",
    "Screenshot after 10 seconds => VRAMx.BMP.": "10秒后截图 => VRAMx.BMP。",
    "Script parameter #1": "脚本参数 #1",
    "Script parameter #2": "脚本参数 #2",
    "Script parameter #3": "脚本参数 #3",
    "Script parameter #4": "脚本参数 #4",
    "Script parameter #5": "脚本参数 #5",
    "Script parameter #6": "脚本参数 #6",
    "Script parameter #7": "脚本参数 #7",
    "Script parameter #8": "脚本参数 #8",
    "Script parameter #9": "脚本参数 #9",
    "Second game for Magic Lantern. Try it in LiveView.": "ML第二个游戏。在实时取景中尝试。",
    "See lv_af_raw, lv_rshd_raw, lv_set_raw, KindOfCraw...": "见lv_af_raw, lv_rshd_raw, lv_set_raw, KindOfCraw...",
    "Select a center-based AF pattern with LEFT and RIGHT keys.": "用左/右键选择中心对焦模式。",
    "Select a file name for playback.": "选择要回放的文件名。",
    "Select a horizontal AF pattern with LEFT and RIGHT keys.": "用左/右键选择水平对焦模式。",
    "Select a vertical AF pattern with LEFT and RIGHT keys.": "用左/右键选择垂直对焦模式。",
    "Select actions for half-shutter.": "选择半按快门操作。",
    "Select an Encoder Config. If off H264.ini will load. Exit menu to apply.": "选择编码器配置。关闭则加载H264.ini。退出菜单应用。",
    "Select the encryption mode. The higher the level, the less comfort you have.": "选择加密模式。级别越高越不方便。",
    "Select whether this script will be loaded at camera startup.": "选择此脚本是否在开机时加载。",
    "Select which PicStyle to use while recording.": "选择录制时使用的照片风格。",
    "Serial Number.": "序列号。",
    "Set GOP size to n frames.": "设置GOP大小为n帧。",
    "Set keyframes by global time (time of day)": "按全局时间(时间)设置关键帧",
    "Set line skipping to get this resolution": "设置跳行以获得此分辨率",
    "Set minimum shutter value.": "设置最慢快门值。",
    "Set the cut off frequency for noise reduction": "设置降噪截止频率",
    "Several helpful image actions you can trigger in PLAY mode.": "回放模式中可触发的多种实用图像操作。",
    "Shift the entire display left and right with EDMAC routines.": "用EDMAC例程左右移动整个显示。",
    "Shoot one image with the hack, one without.": "一张用破解拍摄,一张不用。",
    "Shortcut key for enabling powersave modes right away.": "立即启用省电模式的快捷键。",
    "Show current lens ID. Should match exiftool TEST.CR2 -LensType -b.": "显示当前镜头ID。应与exiftool TEST.CR2 -LensType -b匹配。",
    "Show current lens capability bits.": "显示当前镜头能力位。",
    "Show current lens extender information byte.": "显示当前镜头增距镜信息字节。",
    "Show current lens focal length.": "显示当前镜头焦距。",
    "Show current lens name (as reported by your lens or adapter).": "显示当前镜头名称(由镜头或适配器报告)。",
    "Show current lens serial number. Not all cameras report this.": "显示当前镜头序列号。并非所有相机都报告此项。",
    "Show current lens version string.": "显示当前镜头版本字符串。",
    "Show memory addresses patched in Canon code or data areas.": "显示佳能代码或数据区域中已打补丁的内存地址。",
    "Show properties as they change.": "属性变化时显示。",
    "Show where the white point and the SNR levels are metered": "显示白点和信噪比级别的测光位置",
    "Show/hide script console.": "显示/隐藏脚本控制台。",
    "Shows color distribution as U-V plot. For grading & WB.": "以U-V图显示颜色分布。用于调色和白平衡。",
    "Shutter speed range, when Canon shows 1/30-1/4000.": "快门速度范围,佳能显示1/30-1/4000时。",
    "Sidecar file format, for deflicker metadata.": "附属文件格式,用于去闪烁元数据。",
    "Simple: only consider defocus blur, ignoring diffraction effects.\n": "简单:仅考虑离焦模糊,忽略衍射效应。\n",
    "Simulate minimum aperture value.": "模拟最小光圈值。",
    "Slows down the CF write speed to let you use certain cards.": "降低CF写入速度以使用某些卡。",
    "Sound goes out of sync, so it has to be recorded separately.": "声音会不同步,需独立录制。",
    "Speed for movie Auto ISO. Low values = smooth transitions.": "视频自动ISO速度。低值=平滑过渡。",
    "Start image capture on half-shutter press (quick).\n": "半按快门开始图像捕获(快速)。\n",
    "Start in front or behind focus (varies among lenses)": "从前方或后方开始对焦(因镜头而异)",
    "Start recording": "开始录制",
    "Start recording by pressing shutter halfway. Wired remote.": "半按快门开始录制。有线遥控。",
    "Start scanline (very rough). Use for vertical positioning.": "开始扫描线(很粗糙)。用于垂直定位。",
    "Step 1: achieve critical focus in LiveView with 10x zoom.": "步骤1:在实时取景中用10x缩放实现精准对焦。",
    "Step 2: run this and leave the camera still for ~2 minutes.": "步骤2:运行此功能并保持相机静止约2分钟。",
    "Stop underexposing when at least 5% of the image gets": "当至少5%的图像",
    "Stop underexposing when at least half of the image gets": "当至少一半图像",
    "Strength of ND Filter in EV": "ND滤镜强度(EV)",
    "Stresses graphics bandwith. Run this while recording.": "压力测试图形带宽。录制时运行。",
    "Strong edges: looks for edges, works best in low light.\n": "强边缘:寻找边缘,低光下效果最佳。\n",
    "Subtle image enhancements via DIGIC register tweaks.": "通过DIGIC寄存器微调实现细微图像增强。",
    "Swaps U and V channels (red <--> blue).": "交换U和V通道(红 <--> 蓝)。",
    "Switches INFO screens very quickly.": "快速切换INFO屏幕。",
    "Sync FPS with shutter speed, for long exposures in LiveView.": "FPS与快门速度同步,用于实时取景长曝光。",
    "Take a screenshot for each ML menu.": "为每个ML菜单截图。",
    "Take a silent picture when you press the shutter halfway.\n": "半按快门时拍摄静音照片。\n",
    "Take darker images.\n": "拍摄更暗的图像。\n",
    "Task info: ID, name, priority, wait_id, mem, state.": "任务信息:ID、名称、优先级、等待ID、内存、状态。",
    "Task info: name, priority, stack memory usage.": "任务信息:名称、优先级、栈内存使用。",
    "Tests Canon functions called by ML. SET=once, PLAY=100x.": "测试ML调用的佳能函数。SET=一次,PLAY=100次。",
    "Tests SRM memory allocation routines.": "测试SRM内存分配例程。",
    "Tests proper usage of Canon API calls in ML menu backend.": "测试ML菜单后端中佳能API调用的正确使用。",
    "Tests to make sure Magic Lantern is stable and won't crash.": "测试确保ML稳定不崩溃。",
    "Tests various functions for thread safety. WIP.": "测试各功能的线程安全性。开发中。",
    "The camera may turn into a 1DX or it may explode.": "相机可能变成1DX,也可能爆炸。",
    "The focus offset in steps": "对焦偏移(步数)",
    "The frame at which to apply this keyframe": "应用此关键帧的帧号",
    "The screenshot will contain BMP and YUV overlays.": "截图将包含BMP和YUV叠加。",
    "This changes Canon card selection at startup - nothing else.": "这会更改启动时的佳能卡选择 - 仅此而已。",
    "This checks if the speed drop is indeed caused by cache overflow.": "检查速度下降是否确实由缓存溢出引起。",
    "This feature only works as long as you don't trigger autofocus.": "此功能仅在不触发自动对焦时有效。",
    "This sequence will be auto-loaded at startup.": "此序列将在启动时自动加载。",
    "This used to crash the 500D if the test was run while recording.": "如果在录制时运行测试,曾导致500D崩溃。",
    "This works by lowering ISO => you may get pink highlights.": "通过降低ISO工作 => 可能出现粉色高光。",
    "Timing generator freq. (READ-ONLY). FPS = F/timerA/timerB.": "时序发生器频率(只读)。FPS = F/timerA/timerB。",
    "Tip: in photo mode, it makes LiveView usable in darkness.": "提示:照片模式下使实时取景在黑暗中可用。",
    "Tip: it prevents you from changing it by mistake.": "提示:防止误改。",
    "Tip: load the 'plot' module to get a nice graph.": "提示:加载'plot'模块获得好看的图表。",
    "Tip: set this to -1 for a nice vignette effect.": "提示:设为-1获得好看的暗角效果。",
    "To change this setting: Prefs -> Config options": "更改此设置:偏好 -> 配置选项",
    "To start ramping, press": "开始过渡,按",
    "To trigger, hold shutter pressed halfway for 1 second.": "触发时半按快门1秒。",
    "Too long recording makes empty files on ExFAT, ok on FAT32": "录制太长在ExFAT上产生空文件,FAT32正常",
    "Total memory allocated by ML. Press SET for detailed info.": "ML分配的总内存。按SET查看详情。",
    "Try 75% if you get black borders (e.g. Samyang 8mm on 5D).": "出现黑边时试75%(如三阳8mm在5D上)。",
    "Turn off GlobalDraw when idle, to save some CPU cycles.": "空闲时关闭全局绘制以节省CPU。",
    "Turn off display. Will also pause LiveView if not recording.": "关闭显示。未录制时也将暂停实时取景。",
    "Turn on the front LED [PLAY] or make display bright [SET].": "开启前LED [PLAY] 或调亮显示 [SET]。",
    "Type of waveform to be generated: square, sine, white noise.": "生成的波形类型:方波、正弦波、白噪声。",
    "Use Av+MainDial together to perform selected action.": "同时用Av+主拨盘执行所选操作。",
    "Use for horizontal centering.": "用于水平居中。",
    "Use left & right for minimum. Main dial for maximum.": "左/右设最小值。主拨盘设最大值。",
    "Use smooth exposure transitions, by compensating with ISO.": "用ISO补偿实现平滑曝光过渡。",
    "Use this module with an external intervalometer": "将此模块与外部间隔拍摄器配合使用",
    "Use this to allow spec(ta)cular highlights to be clipped.": "用于允许镜面高光溢出。",
    "Used to compute bulb time from current settings": "用于从当前设置计算B门时间",
    "Useful for long exposures, manual lenses, manual video ctl.": "适用于长曝光、手动镜头、手动视频控制。",
    "Value as 2 x int16. Toggle: changes second value.": "值为2 x int16。切换:更改第二个值。",
    "Value as 4 x int8.": "值为4 x int8。",
    "Value as hex.": "值为十六进制。",
    "Value as int32.": "值为int32。",
    "Value as string.": "值为字符串。",
    "Vignetting correction or effects.": "暗角校正或效果。",
    "Volume for ML beeps and WAV playback (1-5).": "ML提示音和WAV回放音量(1-5)。",
    "Warn if some of your settings are changed by mistake.": "某些设置被误改时警告。",
    "Warn if you change the picture quality to something else.": "画质被改为其他时警告。",
    "Warn if you disable AWB by mistake.": "误禁自动白平衡时警告。",
    "Warn if you enable ALO by mistake.": "误启ALO时警告。",
    "Warn if you turn the mode dial to some other position.": "模式拨盘转到其他位置时警告。",
    "Warn on Manual / Automatic Focus": "手动/自动对焦时警告",
    "Warn type, LED, Messagebox, Beep": "警告类型,LED,消息框,提示音",
    "What ISOs should be available from main menu and shortcuts.": "主菜单和快捷方式中应可用的ISO。",
    "What to display in top-right corner while recording.": "录制时右上角显示什么。",
    "What to do when you press SET and turn the scrollwheel.": "按SET并转动拨盘时的操作。",
    "When enabled it will ask for the encryption password right after camera powerup.": "启用后开机即询问加密密码。",
    "When to display ML overlay graphics (zebra, histogram...)": "何时显示ML叠加图形(斑马纹、直方图...)",
    "When you change Av, ML adjusts Tv and ISO to keep exposure.": "改光圈时ML调整快门和ISO保持曝光。",
    "When you change ISO, ML adjusts Tv and Av to keep exposure.": "改ISO时ML调整快门和光圈保持曝光。",
    "When you change Tv, ML adjusts Av and ISO to keep exposure.": "改快门时ML调整光圈和ISO保持曝光。",
    "When you exit ML menu, or at camera startup.\n": "退出ML菜单时,或开机时。\n",
    "When you press halfshutter exposure will be set.": "半按快门时将设置曝光。",
    "Where to apply the AFMA adjustment.": "应用自动对焦微调的位置。",
    "Where to apply the AFMA adjustment:": "应用自动对焦微调的位置:",
    "Where to meter for deflicking. Recommended: 50% (median).": "去闪烁测光位置。推荐:50%(中位数)。",
    "Where to place the exposure level for processed pics": "处理后的照片曝光电平位置",
    "Which images should get replaced by fake images.": "哪些图像应被替换为假图像。",
    "While recording only. -40...0 dB, yellow -12 dB, red -3 dB.": "仅录制时。-40...0 dB,-12 dB变黄,-3 dB变红。",
    "Will not sync properly in burst mode or when taking pics quickly.": "连拍或快速拍摄时无法正确同步。",
    "With some clever post, you get less shadow noise (more DR).": "通过后期处理可获得更少暗部噪声(更高动态范围)。",
    "With the LCD sensor you may wakeup or force powersave mode.": "用LCD传感器可唤醒或强制省电模式。",
    "Write speed on both CF and SD cards at the same time.": "同时写入CF和SD卡的速度。",
    "Writes 0xBAADBAAD to address 0 (simulating a null pointer error).": "向地址0写入0xBAADBAAD(模拟空指针错误)。",
    "You can draw your own cropmarks in Paint.": "可在画图程序中绘制自己的裁切标记。",
    "You can fine-tune this, but don't expect miracles.": "可微调,但别指望奇迹。",
    "You have to press halfshutter for a while.": "需半按快门一段时间。",
    "You may also have cropmarks in Playback mode.": "回放模式也可使用裁切标记。",
    "You may use the LiveView button to protect images quickly.": "可用实时取景按钮快速保护图像。",
    "You may use the LiveView button to protect or rate images.": "可用实时取景按钮保护或评分图像。",
    "You should clear all keyframes when switching this setting": "切换此设置时应清除所有关键帧",
    "You should have a valid image on the card.": "卡上应有有效图像。",
    "You will need to restart the camera for the changes to take effect.": "需重启相机使更改生效。",
    "You'll have to take the battery out after running most of these.": "运行大部分后需取出电池。",
    "but if you want to optimize the video buffering algorithms, try it.": "但如想优化视频缓冲算法,可尝试。",
    "first-order high pass filter for DC cut": "一阶高通滤波器,用于直流切除",
    "http://www.magiclantern.fm/forum/index.php?topic=9673.0": "http://www.magiclantern.fm/forum/index.php?topic=9673.0",
    "in mids & shadows. It will disable dual ISO if not needed.": "在中调和暗部。如不需要将禁用双ISO。",
    "noisier than selected SNR => will clip more highlights.": "噪声大于选定信噪比 => 会溢出更多高光。",
    "or hold it pressed halfway (enables image stabilization).": "或半按保持(启用防抖)。",
    "second-order high pass filter for noise cut": "二阶高通滤波器,用于降噪",
    "so all your pics look equally exposed, without flicker.": "使所有照片曝光一致,无闪烁。",
}

files = glob.glob(str(ROOT / "src" / "*.c")) + glob.glob(str(ROOT / "modules" / "*" / "*.c"))
total = 0
for f in files:
    p = Path(f)
    try:
        txt = p.read_text(encoding="utf-8")
    except:
        continue
    orig = txt
    for old, new in D.items():
        if old in txt:
            count = txt.count(old)
            txt = txt.replace(old, new)
            total += count
    if txt != orig:
        p.write_text(txt, encoding="utf-8")
print(f"Total replacements: {total}")